alias ll="lsd -l"
alias la="lsd -lA"
alias ll-tree="lsd -l --tree"
alias cat="bat --paging=never"
alias cpufetch="/opt/cpufetch/cpufetch"
alias public-ip="curl -s checkip.dyndns.org | grep -Eo '[0-9.]+'"
