#! /bin/sh

export BROWSER=chromium
export EDITOR=vim
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
~/Source/scripts/bash/change_automatic_wallpaper_one.sh &

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# Hex Gang
hsetroot -solid "#192022"

# I hate mouse drift.
xset m 0 0


my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-A-0' | awk '{print $2}')
if [ $my_laptop_external_monitor = "connected" ]; then
    bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
    bspc monitor eDP -d 0
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pcmanfm desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^3'
bspc rule -a Alacritty desktop='^1'
bspc rule -a jetbrains-idea-ce desktop='^5'
bspc rule -a Firefox desktop='^2'
bspc rule -a DBeaver desktop='^6'
bspc rule -a Slack desktop='^10'

bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &
picom &
dunst &
clipcatd &
~/.config/polybar/launch.sh
deadd-notification-center &
~/scripts/run-notification.sh


disown -a
disown
# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier             Mod4
#rule Code                           desktop=4

config window_gap                   10
config left_padding                 10

config split_ratio                  0.5
config borderless_monocle           true
config gapless_monocle              true
