[colors]

background = #CC071A2E
background-alt = #99152B45
foreground = #D9F3FF
primary = #62D8FF
secondary = #7BE0D5
accent = #A8E6FF
muted = #718CA8
red = #FF6B7A
yellow = #D9E66B
green = #7BE0A8



[bar/main]
width = 100%
height = 28
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 0

padding-left = 1
padding-right = 1

module-margin = 0

font-0 = "Hack:size=10;2"
font-1 = "Symbols Nerd Font:size=11;2"

modules-left = volume player
modules-center = workspaces 
modules-right =  bluetooth cpu date time

separator = "  "
separator-foreground = ${colors.muted}

wm-restack = i3

enable-ipc = true
cursor-click = pointer

; ============================================================
; VOLUME
; ============================================================

[module/volume]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-volume-spacing = 1

label-volume = %percentage%%

ramp-volume-0 = "󰕿"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰕾"

format-muted = "󰖁  muted"
format-muted-foreground = ${colors.muted}

; ============================================================
; PLAYER
; ============================================================

[module/player]
type = custom/script

exec = ~/.config/polybar/scripts/player.sh
tail = true

format = <label>
label = %output%

click-left = playerctl play-pause
click-right = playerctl next
click-middle = playerctl previous

; ============================================================
; WORKSPACES
; ============================================================
[module/workspaces]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true

index-sort = true

enable-click = true
enable-scroll = true

format = <label-state>

label-focused = %name%
label-focused-foreground = ${colors.primary}
label-focused-background = ${colors.background-alt}
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 1

label-visible = %name%
label-visible-foreground = ${colors.secondary}
label-visible-padding = 1

label-urgent = %name%
label-urgent-foreground = ${colors.red}
label-urgent-padding = 1

; ============================================================
; NETWORK
; ============================================================

[module/network]
type = internal/network

interface-type = wireless

interval = 3

format-connected = <label-connected>

label-connected = "󰤨  %essid%"

format-disconnected = "󰤭"
format-disconnected-foreground = ${colors.muted}


; ============================================================
; BLUETOOTH
; ============================================================

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
tail = true
interval = 2
click-left = bluetoothctl power on
click-right = bluetoothctl power off


; ============================================================
; CPU
; ============================================================

[module/cpu]
type = internal/cpu

interval = 2

format = <label>

label = "󰍛  %percentage%%"


; ============================================================
; DATE
; ============================================================

[module/date]
type = internal/date

interval = 1

date = "%d %b - %A"

label = "󰃭  %date%"

locale = es_CO.UTF-8


; ============================================================
; TIME
; ============================================================

[module/time]
type = internal/date

interval = 1

time = "%H:%M"

label = "󰥔  %time%"
