version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "9094:8080"
    volumes:
      - /home/juan-sierra/Zabud/data/jenkins:/var/jenkins_home
