version: '3'

services:

  zookeeper0:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    network_mode: "host"

  kafka0:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    network_mode: "host"

  kafka-ui0:
    image: provectuslabs/kafka-ui
    container_name:  kafka-ui
    ports:
      - 9094:8080
    depends_on:
      - zookeeper0
      - kafka0
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: localhost:2181
    network_mode: "host"

