version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongo-inscription:
    image: mongo:5.0.3-focal
    container_name: mongo-inscription
    ports:
      - "27017:27017"

  activemq:
    image: rmohr/activemq:5.14.0-alpine
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    
  zabud-postgre:
    image: postgres:12.9-alpine
    container_name: postgre_zabud
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - /home/juan-sierra/Zabud/data/postgre_zabud/data:/var/lib/postgresql/data

