#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#run i3lock config
xss-lock --transfer-sleep-lock -- i3lock --nofork

killall copyq
killall flameshot
killall lxqt-powermanagement
killall dunst
killall listeng_port_listeng_diff.sh
killall verify_battery.sh
killall kdeconnect-indicator

flameshot &
lxqt-powermanagement &
dunst &
/usr/lib/polkit-kde-authentication-agent-1 &
/home/juan-sierra/Source/scripts/bash/listeng_port_listeng_diff.sh &
/home/juan-sierra/Source/scripts/bash/verify_battery.sh &
betterlockscreen -u ~/Source/dotfiles/betterlocker/ --display 1 --span &

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
    sh /home/juan-sierra/Source/scripts/bash/change_automatic_wallpaper_one.sh &
fi

index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done

killall picom

kdeconnect-indicator &
copyq &
disown -a
